# Reg2ST / MR-CMR default config
dataset: her2st
dim_in: 1024
dim_hidden: 1024
dim_out: 785
dropout: 0.2
wikg_top: 6
decoder_layer: 6
decoder_head: 8
mask_rate: 0.75
w_con: 0.5
w_zinb: 0.25
epochs: 400
fold: 0
device_id: 0

# MR-CMR specific
neighbor_k: 6
w_fusion: 0.2
